[general]
mode = "development"
invite_code = ""

[server]
port = 8989
allow_origin = [""]

[db]
url = "postgres://postgres:postgres@localhost:5432/matrixbird"

[appservice]
id = "matrixbird_appservice"
sender_localpart = "matrixbird_appservice"
access_token = ""
hs_access_token = ""

[matrix]
homeserver = "http://localhost:8080"
server_name = "localhost:8480"

# Make sure to create this admin user on the homeserver - see synapse docs
[admin]
user = "matrixbird_admin"
password = "strong-password"

[auto_join]
local = true
federated = true

[email.incoming]
enabled = true
domain = "matrixbird.com"

[email.outgoing]
enabled = true
domain = "matrixbird.com"
endpoint = ""

[email.settings]
send_welcome_emails = true

[features.authentication]
registration_enabled = true
require_verification = false
require_invite_code = true

[redis.session]
url = "127.0.0.1:6379/0"
pool_size = 20
timeout_secs = 5

[redis.cache]
url = "127.0.0.1:6379/1"
pool_size = 20
timeout_secs = 5
ttl = 3600

[cache_rules]
well_known = false

[smtp]
account = ""
server = ""
port = 587
username = ""
password = ""

[storage]
access_key_id = ""
access_key_secret = ""
endpoint = ""
bucket = ""
