mode = "development"

[server]
port = 8989
allow_origin = [""]

[db]
url = "postgres://postgres:postgres@localhost:5432/matrixbird"

[appservice]
id = "matrixbird"
sender_localpart = "matrixbird"
access_token = ""
hs_access_token = ""

[matrix]
homeserver = "http://localhost:8080"
server_name = "localhost:8480"

[email]
domain = "matrixbird.com"

[features]
registration_enabled = true
require_verification = false
require_invite_code = true

[redis.session]
url = "127.0.0.1:6379/0"
pool_size = 20
timeout_secs = 5

[mailer]
api_token = ""
account = ""

[smtp]
account = ""
server = ""
port = 587
username = ""
password = ""

[authentication]
invite_code = ""

