mode = "development"

[server]
port = 8989
allow_origin = [""]

[db]
url = "postgres://postgres:postgres@localhost:5432/matrixbird"

[appservice]
id = "matrixbird"
sender_localpart = "matrixbird"
access_token = ""
hs_access_token = ""

[matrix]
homeserver = "http://localhost:8080"
server_name = "localhost:8480"

[email]
send_welcome_emails = true

[email.incoming]
enabled = true
domain = "matrixbird.com"

[email.outgoing]
enabled = true
domain = "matrixbird.com"
endpoint = ""

[email.settings]
send_welcome_emails = true

[features.authentication]
registration_enabled = true
require_verification = false
require_invite_code = true
invite_code = ""

[redis.session]
url = "127.0.0.1:6379/0"
pool_size = 20
timeout_secs = 5

[redis.cache]
url = "127.0.0.1:6379/1"
pool_size = 20
timeout_secs = 5
ttl = 3600

[cache_rules]
well_known = false

[smtp]
account = ""
server = ""
port = 587
username = ""
password = ""
