DROP INDEX IF EXISTS idx_events_event_id;
DROP INDEX IF EXISTS idx_events_room_id;
DROP INDEX IF EXISTS idx_events_type;
DROP INDEX IF EXISTS idx_events_sender;
DROP INDEX IF EXISTS idx_events_recipients;
DROP INDEX IF EXISTS idx_events_relates_to_event_id
DROP INDEX IF EXISTS idx_events_in_reply_to;
DROP INDEX IF EXISTS idx_events_rel_type;
DROP INDEX IF EXISTS idx_events_message_id;
DROP INDEX IF EXISTS idx_events_created_at;
DROP INDEX IF EXISTS idx_events_jsonb;
DROP TABLE IF EXISTS events;
