name: Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'build.rs'
      - '.github/workflows/**'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Binary

    runs-on: ubuntu-24.04-arm

    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
        
    - name: Build 
      run: cargo build --release

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: matrixbird
        path: target/release/matrixbird
