name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H "${{ secrets.VPS_HOST }}" >> ~/.ssh/known_hosts

    - name: Deploy and Build on VPS
      run: |
       ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} <<EOF
       cd /home/${{ secrets.VPS_USER }}/server
       git pull
       cargo build --release
       rm ./matrixbird
       cp ./target/release/matrixbird .
       cd /home/${{ secrets.VPS_USER }}/matrixbird.net/server
       git pull
       rm ./matrixbird
       cp ../../server/matrixbird .
       cd /home/${{ secrets.VPS_USER }}/matrixbird.dev/server
       git pull
       rm ./matrixbird
       cp ../../server/matrixbird .
       EOF
