name: Deploy

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'build.rs'
      - '.github/workflows/deploy.yml'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Binary

    runs-on: ubuntu-24.04-arm

    permissions:
      contents: read

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
        
    - name: Build 
      run: cargo build --release

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: matrixbird
        path: target/release/matrixbird

  upload:
    name: Upload Binary
    runs-on: ubuntu-24.04

    needs:
      - build

    permissions:
      contents: read

    steps:

    - name: Download binary
      uses: actions/download-artifact@v4
      with:
        name: matrixbird
        path: .
      
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H "${{ secrets.VPS_HOST }}" >> ~/.ssh/known_hosts

    - name: Update repos & copy binary 
      run: |
       ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} <<EOF
       cd /home/${{ secrets.VPS_USER }}/matrixbird.com/server
       git pull
       cd /home/${{ secrets.VPS_USER }}/matrixbird.net/server
       git pull
       cd /home/${{ secrets.VPS_USER }}/matrixbird.dev/server
       git pull
       EOF

    - name: Upload binary 
      run: |
        rsync -avz --progress matrixbird ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USER }}/matrixbird.com/server/
        rsync -avz --progress matrixbird ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USER }}/matrixbird.net/server/
        rsync -avz --progress matrixbird ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USER }}/matrixbird.dev/server/
