name: Deploy

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'build.rs'
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-24.04-arm

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
        
    - name: Build 
      run: cargo build --release
      
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H "${{ secrets.VPS_HOST }}" >> ~/.ssh/known_hosts

    - name: Update repos & copy binary 
      run: |
       ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} <<EOF
       cd /home/${{ secrets.VPS_USER }}/matrixbird.com/server
       rm ./matrixbird
       git pull
       cd /home/${{ secrets.VPS_USER }}/matrixbird.net/server
       rm ./matrixbird
       git pull
       cd /home/${{ secrets.VPS_USER }}/matrixbird.dev/server
       rm ./matrixbird
       git pull
       EOF

    - name: Upload binary 
      run: |
        scp target/release/matrixbird ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USER }}/matrixbird.com/server/matrixbird
        scp target/release/matrixbird ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USER }}/matrixbird.net/server/matrixbird
        scp target/release/matrixbird ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USER }}/matrixbird.dev/server/matrixbird
